import os
from pathlib import Path
from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response
from dotenv import load_dotenv

script_dir = Path(__file__).resolve().parent
main_dir = script_dir.parent
dotenv_path = main_dir / ".env"
load_dotenv(dotenv_path=dotenv_path)

class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    def __init__(self, app):
        super().__init__(app)
        self.environment = os.getenv("ENVIRONMENT", "development")
        
    async def dispatch(self, request: Request, call_next):
        response: Response = await call_next(request)

        # Read the nonce generated by the set_csp_nonce middleware in app.py.
        # request.state is backed by the shared ASGI scope dict, so inner-middleware
        # mutations are always visible here after call_next returns.
        nonce = getattr(request.state, 'csp_nonce', '')
        
        # Basic security headers that work for most cases
        headers = {
            "X-Frame-Options": "DENY",
            "X-Content-Type-Options": "nosniff", 
            "Referrer-Policy": "strict-origin-when-cross-origin",
            "X-XSS-Protection": "1; mode=block",
            "X-Permitted-Cross-Domain-Policies": "none",
            "Permissions-Policy": (
                "geolocation=(), microphone=(), camera=(), payment=(), "
                "usb=(), magnetometer=(), accelerometer=(), gyroscope=(), "
                "fullscreen=(self)"
            ),
            "Content-Security-Policy": (
                "default-src 'self'; "
                f"script-src 'self' 'nonce-{nonce}' https://discord.com https://discordapp.com https://www.google.com https://www.gstatic.com; "
                "style-src 'self' 'unsafe-inline'; "
                "img-src 'self' data: https: blob:; "
                "font-src 'self' data:; "
                "connect-src 'self' https://discord.com https://discordapp.com; "
                "frame-src 'self' https://discord.com https://discordapp.com https://www.google.com; "
                "media-src 'self'; "
                "object-src 'none'; "
                "base-uri 'self'; "
                "form-action 'self'; "
                "frame-ancestors 'none'"
            )
        }
        
        # Add HSTS only if in production (you can adjust this based on your config)
        if self.environment == 'production':
            headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains; preload"
        
        # Apply all headers
        for header_name, header_value in headers.items():
            response.headers[header_name] = header_value
        
        # Cache control for admin areas
        if request.url.path.startswith(('/admin', '/api/admin')):
            response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, proxy-revalidate"
            response.headers["Pragma"] = "no-cache" 
            response.headers["Expires"] = "0"
            
        return response